#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

#Activate VirtualEnv in order to use the correct libraries
source $OPENSHIFT_GEAR_DIR/virtenv/bin/activate
export PYTHON_EGG_CACHE=$OPENSHIFT_GEAR_DIR/virtenv/lib/python-2.6

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py syncdb --noinput'"
python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py syncdb --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py collectstatic --noinput'"
python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py collectstatic --noinput

python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py createsuperuser --username=admin --noinput --email me@example.org
python $OPENSHIFT_REPO_DIR/wsgi/openshift/manage.py changepassword admin